### ISSUE TITLE
Find better ways to mark the attendance

### ISSUE THREAD

**Issue by Vaarun-Kamath** [acmpesuecc/Attendance-Register#2]
- As of now the website takes individual entries of individual student, although this is a good use case for some classes like one-on-one classes, some teachers teach to a bunch of students at once, which makes it hard for them to mark multiple students. 
- Have another option where the user can mark multiple students at once, kind of like how PES lecturers mark attendance.

**Comment by Vaarun-Kamath** [comment]
@itsA-D you have been assigned

**Comment by shreyahegde26** [comment]
could i get assigned to this?

**Comment by shivyy2283** [comment]
can u assign this to me?

**Comment by Varshith100** [comment]
i want to do this

**Comment by uditreddys** [comment]
i want to work on this

**Comment by ankitam389** [comment]
can i get assigned this?

**Comment by sachint19004** [comment]
can I get assigned to this ?

**Comment by diishanbhag** [comment]
please assign this to me

**Comment by sid-nc** [comment]
can i get assigned

**Comment by taruunb** [comment]
can i be assigned to this?

**Comment by Vaarun-Kamath** [comment]
@itsA-D I will need an update by 9. Else I will reassign the issue

**Comment by siri-n-shetty** [comment]
Could you please assign this to me?

**Comment by akdino** [comment]
can i get assigned

**Comment by 411sst** [comment]
can i get assigned if this is still open?
