### ISSUE TITLE
There are 3 features one below the other which makes it less convenient. Make different tabs for each feature

### ISSUE THREAD

**Issue by Vaarun-Kamath** [acmpesuecc/Attendance-Register#3]
Features include:
- Student Attendance Recording
- Attendance Record Display
- New Student Entry

Refer to the Streamlit documentation: https://docs.streamlit.io/

**Comment by neethanm** [comment]
hey, can i be assigned this issue

**Comment by Vaarun-Kamath** [comment]
@neethanm you have been assigned

**Comment by kavs2803** [comment]
can i be work on this issue ?

**Comment by sid-nc** [comment]
can i get assigned

**Comment by neethanm** [comment]
I have created a pull request to after changing main.py file.
This displays different features in different tabs.
![image](https://github.com/acmpesuecc/Attendance-Register/assets/100505296/2b0dc4d5-71ac-4503-a1d8-c2595a626ced)

**Comment by taruunb** [comment]
can i be assigned

**Comment by M-SriVidya** [comment]
can i please get assigned

**Comment by ananyashreyaz** [comment]
can I get assigned?
