### ISSUE TITLE
AttendanceRecord.xlsx does not exist

### ISSUE THREAD

**Issue by Vaarun-Kamath** [acmpesuecc/Attendance-Register#6]
# Description
The website only registers attendance if the AttendanceRecord.xlsx file is already present in the folder, if not present it gives an error. Fix this to make it such that it creates an excel file if the file does not exist

**Comment by AshwinaRakish** [comment]
hey, can you pls assign this issue to me

**Comment by kavs2803** [comment]
hey can i be assigned this issue please

**Comment by Vaarun-Kamath** [comment]
@AshwinaRakish you have been assigned

**Comment by neethanm** [comment]
Hey, can this issue be assigned to me?

**Comment by SafwanAhmed08** [comment]
can I get assigned to this issue please

**Comment by sid-nc** [comment]
can i get assigned

**Comment by euphoricair7** [comment]
Could You assign me this issue?
