### ISSUE TITLE
The application takes 0 minute class

### ISSUE THREAD

**Issue by Vaarun-Kamath** [acmpesuecc/Attendance-Register#7]
# Description
When filling the attendance for a student, the sliding bar takes 0 as well, but there cannot be an attendance for 0 minute class
- Refer to the streamlit documentation for possible solutions: https://docs.streamlit.io/

**Comment by ankitkumar099** [comment]
can u assign this to me

**Comment by ankitkumar099** [comment]
can u assign me again

**Comment by Vaarun-Kamath** [comment]
You have been assigned

**Comment by sid-nc** [comment]
can u assign this to me

**Comment by ZeusOp23** [comment]
can you assign this to me

**Comment by euphoricair7** [comment]
Could You assign me this issue?

**Comment by Aakriti-2334** [comment]
can you assign it to me?

**Comment by 825pranav** [comment]
Hey,  Could You assign me this issue?

**Comment by ankitkumar099** [comment]
your attendance.excel file is missing

**Comment by Vaarun-Kamath** [comment]
@ankitkumar099 you can make the excel file, the file name is present in the code.

**Comment by Vaarun-Kamath** [comment]
I will need an update by 9, else I will reassign this issue

**Comment by Vaarun-Kamath** [comment]
@ankitkumar099 you have not given me an update. I am reassigning this issue.

**Comment by Vaarun-Kamath** [comment]
@ZeusOp23 You have been assigned

**Comment by siri-n-shetty** [comment]
Could you please assign this to me?

**Comment by siri-n-shetty** [comment]
Could you please assign this to me?

**Comment by akdino** [comment]
can i get assigned to this pls?

**Comment by melvinjjoseph** [comment]
can i get assigned to this

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by 7Akshu77** [comment]
Can I get assigned to this issue

**Comment by Vaarun-Kamath** [comment]
@7Akshu77 you have been assigned

**Comment by 7Akshu77** [comment]
yes

**Comment by UdayaPragna** [comment]
could i be assinged for this issue

**Comment by shakirth-anisha** [comment]
can you assign this to me??

**Comment by siri-n-shetty** [comment]
Could you please assign this to me?

**Comment by Vaarun-Kamath** [comment]
@siri-n-shetty You have been assigned

**Comment by N0Xl0US** [comment]
assign pls i am done

**Comment by nik2203** [comment]
Could I be assigned to this please?

**Comment by diishanbhag** [comment]
please assign this to me

**Comment by swayamchhaba** [comment]
hey can i work on this task

**Comment by siri-n-shetty** [comment]
I have made a pr, could you please check it @Vaarun-Kamath
